const successMessages = {
  USER_REGISTERED_SUCCESSFULLY:
    "User registered successfully. Please check your email for verification.",
  DEALER_REGISTERED_SUCCESSFULLY: "Dealer registered successfully",
  DEALER_FETCHED_SUCCESSFULLY: "Dealer fetched successfully",
  DEALER_UPDATED_SUCCESSFULLY: "Dealer updated successfully",
  USER_CREATED_SUCCESSFULLY: "User created successfully",
  LOGIN_SUCCESSFUL: "Login successful",
  PASSWORD_CREATED_SUCCESSFUL: "Password created successful",
  TOKENS_REFRESHED: "Tokens refreshed successfully",
  LOGOUT_SUCCESSFUL: "Logout successful",
  PASSWORD_VERIFIED: "Password verified",
  VERIFICATION_CODE_SENT: "Verification code sent",
  DEALER_EMAIL_VERIFIED: "Email verified",
  EMAIL_VERIFIED_SUCCESSFULLY: "Email verified successfully",
  FORGOT_PASSWORD_EMAIL_SENT:
    "If an account exists, we sent a reset link",
  RESET_TOKEN_VALID: "Reset token is valid",
  PASSWORD_RESET_SUCCESSFUL: "Password reset successfully",
  USERS_FETCHED_SUCCESSFULLY: "Users fetched successfully",
  USER_FETCHED_SUCCESSFULLY: "User fetched successfully",
  USER_UPDATED_SUCCESSFULLY: "User updated successfully",
  USER_DELETED_SUCCESSFULLY: "User deleted successfully",
  WAREHOUSE_CREATED_SUCCESSFULLY: "Warehouse created successfully",
  WAREHOUSES_FETCHED_SUCCESSFULLY: "Warehouses fetched successfully",
  WAREHOUSE_FETCHED_SUCCESSFULLY: "Warehouse fetched successfully",
  WAREHOUSE_UPDATED_SUCCESSFULLY: "Warehouse updated successfully",
  WAREHOUSE_DELETED_SUCCESSFULLY: "Warehouse deleted successfully",
  MANUFACTURER_CREATED_SUCCESSFULLY: "Manufacturer created successfully",
  MANUFACTURERS_FETCHED_SUCCESSFULLY: "Manufacturers fetched successfully",
  MANUFACTURER_FETCHED_SUCCESSFULLY: "Manufacturer fetched successfully",
  MANUFACTURER_UPDATED_SUCCESSFULLY: "Manufacturer updated successfully",
  MANUFACTURER_DELETED_SUCCESSFULLY: "Manufacturer deleted successfully",
  SHOP_CREATED_SUCCESSFULLY: "Shop created successfully",
  SHOPS_FETCHED_SUCCESSFULLY: "Shops fetched successfully",
  SHOP_FETCHED_SUCCESSFULLY: "Shop fetched successfully",
  SHOP_UPDATED_SUCCESSFULLY: "Shop updated successfully",
  SHOP_DELETED_SUCCESSFULLY: "Shop deleted successfully",
  PRODUCT_CREATED_SUCCESSFULLY: "Product created successfully",
  PRODUCTS_CREATED_SUCCESSFULLY: "Products created successfully",
  PRODUCTS_FETCHED_SUCCESSFULLY: "Products fetched successfully",
  PRODUCT_FETCHED_SUCCESSFULLY: "Product fetched successfully",
  PRODUCT_UPDATED_SUCCESSFULLY: "Product updated successfully",
  PRODUCT_DELETED_SUCCESSFULLY: "Product deleted successfully",
  INVENTORY_FETCHED_SUCCESSFULLY: "Inventory fetched successfully",
  AVAILABLE_STOCK_FETCHED_SUCCESSFULLY: "Available stock fetched successfully",
  INVENTORY_ADJUSTED_SUCCESSFULLY: "Inventory adjusted successfully",
  DASHBOARD_STATS_FETCHED_SUCCESSFULLY: "Dashboard stats fetched successfully",
  STOCK_MOVEMENTS_FETCHED_SUCCESSFULLY: "Stock movements fetched successfully",
  PURCHASE_ORDER_CREATED_SUCCESSFULLY: "Purchase order created successfully",
  PURCHASE_ORDERS_FETCHED_SUCCESSFULLY: "Purchase orders fetched successfully",
  PURCHASE_ORDER_FETCHED_SUCCESSFULLY: "Purchase order fetched successfully",
  PURCHASE_ORDER_SUBMITTED_SUCCESSFULLY: "Purchase order submitted successfully",
  GRN_RECEIVED_SUCCESSFULLY: "Goods received successfully",
  PURCHASE_ORDER_CANCELLED_SUCCESSFULLY: "Purchase order cancelled successfully",
  SALES_ORDER_CREATED_SUCCESSFULLY: "Sales order created successfully",
  SALES_ORDER_UPDATED_SUCCESSFULLY: "Sales order updated successfully",
  SALES_ORDERS_FETCHED_SUCCESSFULLY: "Sales orders fetched successfully",
  SALES_ORDER_FETCHED_SUCCESSFULLY: "Sales order fetched successfully",
  SALES_ORDER_APPROVED_SUCCESSFULLY: "Sales order approved successfully",
  SALES_ORDER_PICKING_STARTED: "Sales order picking started",
  SALES_ORDER_SHIPPED_SUCCESSFULLY: "Sales order shipped successfully",
  SALES_ORDER_DELIVERED_SUCCESSFULLY: "Sales order delivered successfully",
  SALES_ORDER_CANCELLED_SUCCESSFULLY: "Sales order cancelled successfully",
};

const errorMessages = {
  PERMISSION_DENIED: "Permission Denied",
  RESET_TOKEN_INVALID: "Reset token is invalid or has expired.",
  FAILED_TO_SEND_RESET_LINK: "Failed to send reset link",
  RESET_PASSWORD_FAILED: "Reset password failed",
  TOKEN_EXPIRED: "Token is invalid or has expired",
  NO_CHANGES: "No changes detected",
  CREATE_UNSUCCESSFUL: "Create unsuccessful",
  UPDATE_UNSUCCESSFUL: "Update unsuccessful",
  DELETE_UNSUCCESSFUL: "Delete unsuccessful",
  INVALID_CREDENTIALS: "Invalid credentials",
  NOT_VERIFIED: "User not verified ",
  INACTIVE_ACCOUNT: "This account is currently inactive.",
  ACCESS_DENIED: "Access denied",
  EMAIL_ALREADY_EXISTS: "Email already exists",
  PHONE_NUMBER_ALREADY_EXISTS: "Phone number already exists",
  USER_EMAIL_EXISTS: "User with this email already exists",
  USER_CREATION_FAILED: "An unexpected error occurred during user creation.",
  DEALER_EMAIL_EXISTS: "Dealer with this email already exists",
  DEALER_EMAIL_UNCHANGED: "The new email matches your current dealer email",
  DEALER_EMAIL_OTP_INVALID: "Verification code is invalid or has expired",
  DEALER_EMAIL_OTP_REQUIRED: "Email change requires verification",
  DEALER_EMAIL_OTP_RATE_LIMITED: "Please wait before requesting another code",
  FAILED_TO_SEND_VERIFICATION_CODE: "Failed to send verification code",
  USER_NOT_FOUND: "User not found",
  DEALER_NOT_FOUND: "Dealer not found",
  WAREHOUSE_NOT_FOUND: "Warehouse not found",
  CANNOT_DELETE_DEFAULT_WAREHOUSE: "Cannot delete the default warehouse",
  MANUFACTURER_NOT_FOUND: "Manufacturer not found",
  SHOP_NOT_FOUND: "Shop not found",
  PRODUCT_NOT_FOUND: "Product not found",
  PRODUCT_SKU_EXISTS: "Product SKU already exists",
  PRODUCT_CSV_REQUIRED: "CSV file is required",
  PRODUCT_CSV_INVALID: "Unable to parse the CSV file",
  PRODUCT_CSV_EMPTY: "CSV file contains no product rows",
  PRODUCT_CSV_MISSING_COLUMNS: "CSV must include sku and name columns",
  PRODUCT_CSV_TOO_MANY_ROWS: "CSV exceeds the maximum of 1000 products",
  INVENTORY_NOT_FOUND: "Inventory record not found",
  INSUFFICIENT_STOCK: "Insufficient stock available",
  PURCHASE_ORDER_NOT_FOUND: "Purchase order not found",
  PO_ITEM_NOT_FOUND: "Purchase order item not found",
  GRN_QUANTITY_EXCEEDS_ORDER: "Received quantity exceeds remaining order quantity",
  GRN_DUPLICATE_ITEMS: "Each purchase order item can appear only once in a GRN",
  ADJUSTMENT_BELOW_ALLOCATED:
    "Cannot reduce on-hand stock below the allocated quantity",
  INVALID_PO_STATUS_TRANSITION: "Invalid purchase order status transition",
  SALES_ORDER_NOT_FOUND: "Sales order not found",
  SALES_ORDER_NOT_EDITABLE: "Only pending sales orders can be edited",
  INVALID_SO_STATUS_TRANSITION: "Invalid sales order status transition",
  CREDIT_LIMIT_EXCEEDED: "Credit limit exceeded for this shop",
  USER_UPDATE_FAILED: "An unexpected error occurred during user update.",
  USER_DELETE_FAILED: "An unexpected error occurred during user deletion.",
};

export const emailSubject = {
  EMAIL_VERIFICATION: "Welcome to DWMS – Please Verify Your Email Address",
  PASSWORD_RESET: "Reset your DWMS password",
  DEALER_EMAIL_OTP: "Your DWMS email verification code",
};

export const emailTemplate = {
  EMAIL_VERIFICATION: "email-verification",
  PASSWORD_RESET: "password-reset",
  DEALER_EMAIL_OTP: "dealer-email-otp",
};

export { successMessages, errorMessages };
